<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_look = $this->getLook(); ?>
<div> <?php echo $_look->getTitle(); ?></div>
<div> <img src="<?php echo Mage::getBaseUrl('media') . DS . 'lookbook' . DS . $_look->getImage(); ?>" /></div>
<?php foreach ($_look->getProducts() as $_product): ?>
    <?php $this->setProduct($_product); ?>
    <script type="text/javascript">
        var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
    </script>
    <div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
    <div class="product-view">
        <div class="product-essential">
            <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if ($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
                <div class="no-display">
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </div>

                <div class="product-shop">
                    <div class="product-name">
                        <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
                    </div>

                    <?php if ($this->canEmailToFriend()): ?>
                        <p class="email-friend"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
                    <?php endif; ?>

                    <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
                    <?php $this->getChild('alert_urls')->setData('product', $_product);
                    echo $this->getChildHtml('alert_urls', false) ?>
                    <?php $this->getChildHtml('product_type_data', false) ?>
                    <?php if ($_product->isAvailable()): ?>
                        <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product) ?>
                    <?php echo $this->getTierPriceHtml() ?>
                    <?php echo $this->getChildHtml('extrahint') ?>

                        <?php if (!$this->hasOptions()): ?>
                        <div class="add-to-box">
                            <?php if ($_product->isSaleable()): ?>
                                <?php $this->getChild('addtocart')->setData('product', $_product);
                                echo $this->getChildHtml('addtocart', false)
                                ?>
                                <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl = $this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                    <span class="or"><?php echo $this->__('OR') ?></span>
                                <?php endif; ?>
                        <?php endif; ?>
                        <?php $this->getChild('addto')->setData('product', $_product);
                        echo $this->getChildHtml('addto', false) ?>
                        </div>
                            <?php echo $this->getChildHtml('extra_buttons') ?>
                    <?php elseif (!$_product->isSaleable()): ?>
                        <div class="add-to-box">
                        <?php $this->getChild('addto')->setData('product', $_product);
                        echo $this->getChildHtml('addto', false) ?>
                        </div>
    <?php endif; ?>

                    <?php if ($_product->getShortDescription()): ?>
                        <div class="short-description">
                            <h2><?php echo $this->__('Quick Overview') ?></h2>
                            <div class="std"><?php echo $_helper->productAttribute($_product, nl2br($_product->getShortDescription()), 'short_description') ?></div>
                        </div>
                    <?php endif; ?>

                    <?php echo $this->getChildHtml('other'); ?>

                    <?php if ($_product->isSaleable() && $this->hasOptions()): ?>
                        <?php
                        $this->getChild('product_options_wrapper')->setData('product', $_product);
                        echo $this->getChildHtml('product_options_wrapper', false);

                        $this->getChild('product_options_wrapper_bottom')->setData('product', $_product);
                        echo $this->getChildHtml('product_options_wrapper_bottom', false);
//echo $this->getChildChildHtml('container1', '', true, true) 
                        ?>
                    <?php endif; ?>

                </div>

                <div class="product-img-box">

    <?php $this->getChild('media')->setData('product', $_product);
    echo $this->getChildHtml('media', false) ?>
                </div>

                <div class="clearer"></div>

            </form>
            <script type="text/javascript">
                //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                            form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
                //]]>
            </script>
        </div>


    </div>
<?php endforeach; ?>
