<?php
/**
 * Lookbook list template
 *
 * @see Magazento_Lookbook_Block_Product_List
 */
?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="lookbook">
   
    

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
           
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
               <a href="<?php echo Mage::getUrl('lookbook/index/view',array('id'=>$_product->getId())) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <img src="<?php echo Mage::getBaseUrl('media') . DS . 'lookbook' . DS.$_product->getMainImage(); ?>" alt="<?php echo $this->stripTags($_product->getTitle()) ?>" /></a>
            <h2 class="product-name">  <a href="<?php echo Mage::getUrl('lookbook/index/view', array('id' => $_product->getId())) ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $_product->getTitle()?></a></h2>
               
               
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
