<?php
/**
 * Lookbook list template
 *
 * @see Magazento_Lookbook_Block_Product_List
 */
?>

<?php
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="lookbook">
       
 <?php $i=0; foreach ($_productCollection as $_product): ?>
                <?php if ($i % Mage::getStoreConfig('lookbook/front/rowcnt') == 0 ): ?>
        <div class="row">
            <?php endif;?>
                <div class = 'item' id="item<?php echo $i; ?>">
                    <a href="<?php echo Mage::getUrl('lookbook/index/view',array('id'=>$_product->getId())) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <img src="<?php echo Mage::getBaseUrl('media') . DS . 'lookbook' . DS.$_product->getMainImage(); ?>" alt="<?php echo $this->stripTags($_product->getTitle()) ?>" /></a>
            <h2 class="product-name">  <a href="<?php echo Mage::getUrl('lookbook/index/view', array('id' => $_product->getId())) ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $_product->getTitle()?></a></h2>
               
               
                </div>
             <?php if ($i % Mage::getStoreConfig('lookbook/front/rowcnt') == Mage::getStoreConfig('lookbook/front/rowcnt')-1 ): ?>
        </div>
            <?php endif;
            $i++;?>  
              <?php endforeach; ?>
  <?php if ($i % Mage::getStoreConfig('lookbook/front/rowcnt') <> Mage::getStoreConfig('lookbook/front/rowcnt')-1 ): ?>
        </div>
            <?php endif; ?>
          
    </div>
<?php endif; ?>
